### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by aaaaamilk** [k2-fsa/libriheavy#1]
Author, can you please provide specific instructions on how to use this dataset? I would greatly appreciate it.

**Comment by pkufool** [comment]
Please wait for another two days. I'm writing the documents.

**Comment by aaaaamilk** [comment]
ok,thanks

**Comment by pkufool** [comment]
FYI:
The alignment pipeline: https://github.com/k2-fsa/text_search/tree/master/examples/libriheavy
Metadata: http://huggingface.co/datasets/pkufool/libriheavy
Paper: https://arxiv.org/abs/2309.08105
